# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)

User.all.each { |u| u.destroy }
Title.all.each { |t| t.destroy }
Illustration.all.each { |i| i.destroy }

@one = User.create!(:email => '1@2.com', :password => 'blargh')
@two = User.create!(:email => '1@3.com', :password => 'blargh')

Title.create!(:title => 'Motherhood: The Moral Abyss', :user => @one)
Title.create!(:title => 'Squirrels: The Stretchiest Of All The Mammals *your guide to endless pleasure*', :user => @one)
Title.create!(:title => 'The Fascist\'s Guide To Ladies Night', :user => @one)
Title.create!(:title => 'Crude Oil Superior To Breast Milk: Finally, Nutritionists Confirm What We All Suspected', :user => @one)
Title.create!(:title => 'Achieve Inner Peace And Tranquility Through Tailgating', :user => @one)
Title.create!(:title => 'Headbutting - The Mating Dominance Tactic Used By Hundreds Of Species, And The Cause Of Male Baldness, Which Sucks: Why Women Shouldn\'t Dress Immodestly And Inflame Male Passions, So Us Dudes Can Hang On To Our Hair', :user => @one)
Title.create!(:title => 'A Bold New Look At History: Proof The Mongol Hordes Rode Into Battle On Gerbils', :user => @one)
Title.create!(:title => 'Autopsies: The Ultimate Party Game', :user => @one)
Title.create!(:title => 'Petrol Saving Tips: Glue Your Car To Buses, Let Them Tow You', :user => @one)
Title.create!(:title => 'The Ultimate Exercise Guide: Harpoon Yourself Fit', :user => @one)
Title.create!(:title => 'The Ultimate Study Guide: Waterboard Yourself Smart', :user => @one)
Title.create!(:title => 'The Ultimate Diet Guide: Taser Yourself Thin', :user => @one)
Title.create!(:title => 'Breast Milk Or Red Bull+Vodka: What Would Your Baby *Really* Prefer, And Why Would You Deny That Which He Loves? Just What Sort Of Parent Are You, Anyway?', :user => @one)
Title.create!(:title => 'The Ground Glass Diet: Mix This Delightful Supplement Into Your Coworkers\' Lunches', :user => @one)
Title.create!(:title => 'Apocalypse Training: Help Your Friends And Coworkers Acclimatise With Thoughtfully Placed Thermite', :user => @one)
Title.create!(:title => 'Genocide: Your One-Way Ticket To Heaven! Seriously, Who Doesn\'t Like Genocide?', :user => @one)
Title.create!(:title => 'The Octopus\'s Guide To Orgies', :user => @one)
Title.create!(:title => 'Crushing The Imminent Baboon Uprising: Peace Through Strength', :user => @one)
Title.create!(:title => 'Molotov Cocktails: The *Discerning* Man\'s Guide To Kindergarten Discipline', :user => @one)
Title.create!(:title => 'Harnessing The Homosexual Agenda For Personal Gain', :user => @one)
Title.create!(:title => 'Everyone Around You Is Secretly A Lizard: Pragmatism At Its Finest', :user => @one)
Title.create!(:title => 'Nitrous Oxide: The *Thinking* Man\'s Beverage', :user => @one)
Title.create!(:title => 'The Queen Mother\'s Flying Trapeze Extravaganza', :user => @one)
Title.create!(:title => 'Beelzebub\'s Buttcheeks: The Cauldron Of Possibilities', :user => @one)
Title.create!(:title => 'Scream Yourself Slim: Blowing Your Top The Healthy Way', :user => @one)
Title.create!(:title => 'Shocking Proof That Lightning Is Gay', :user => @one)
Title.create!(:title => 'How To Sell *Other* People\'s Souls: Your Guide To Deceiving Satan For Fun, Profit And Power Eternal', :user => @one)
Title.create!(:title => 'Orgasms: Proof Jesus Hates You', :user => @one)
Title.create!(:title => 'Understanding Men: A Task In Futility', :user => @one)
Title.create!(:title => 'Breaking The Biological Sound Barrier: An Epic Tale Of Sellotaping Together Racehorses To Combine And Add Their Speed', :user => @one)
Title.create!(:title => 'Why Ahmadinejad Has Ordered Nuclear Strikes On His Thumb', :user => @one)
Title.create!(:title => 'Can Donald Trump Swallow The USS Kitty Hawk Without Dislocating His Jaw? The Answer May Surprise You!', :user => @one)
Title.create!(:title => 'Britain Secretly Made Of Vodka: The Royal Family\'s Ninth Darkest Secret', :user => @one)
Title.create!(:title => 'The Coming Jewish Tabasco Sauce Floods And How To Contain Them: Why Israel *Really* Built Its "Security" Walls', :user => @one)
Title.create!(:title => 'Sparrows: Humanity\'s Deadliest Threat: Seriously, Those Fuckers Can Carry Off Tanks', :user => @one)
Title.create!(:title => 'Human Brains Can Be Replaced By Spongecakes With No Ill Effect: The Shocking Truth Psychologist "Experts" Don\'t Want You To Know', :user => @one)
Title.create!(:title => 'Neurons Actually Bonsai Gibbons, A Conspiracy Unmasked', :user => @one)
Title.create!(:title => '[for psychologists] Freud Was Right All Along! Admit It, Everyone Loves His Sexy Sexy Theories', :user => @one)
Title.create!(:title => 'Arson On A Budget, The World On A Plate: How Gandhi Torched His Way Into The History Books', :user => @one)
Title.create!(:title => 'Mr T Is Made Of Chocolate: A Bold New Study', :user => @one)
Title.create!(:title => '[one of Miriam\'s] Shitbag: A Colostomy Odyssey', :user => @one)
Title.create!(:title => 'You\'ve Never Seen Rumsfeld And Megatron In The Same Room Together: We Reveal Why', :user => @one)
Title.create!(:title => 'Skinheads Who Just Want To Be Loved', :user => @one)
Title.create!(:title => 'Fighting Sodomy The Fabulous Way', :user => @one)
Title.create!(:title => 'Klansmen For Justice: One Innocent Movement\'s Cruel Persecution', :user => @one)
Title.create!(:title => 'The Little Nazi Who Could', :user => @one)
Title.create!(:title => '[caption to an apocalypse scene, or sinking of the Titanic] See, This Is What Happens When You Give Women The Vote', :user => @one)
Title.create!(:title => 'Prejudice Part 2: Universal Suffrage - A Cruel Experiment Gone Tragically Wrong', :user => @one)
Title.create!(:title => 'Prejudice Part 3: Desegregation - Civilised Man\'s Greatest Blunder', :user => @one)
Title.create!(:title => 'Inducing Shark Attacks On The Steppes Of Mongolia', :user => @one)
Title.create!(:title => 'Sometimes Arson Is The Opposite Of Helpful', :user => @one)
Title.create!(:title => 'The Westboro Baptist\'s Guide To Fellatio', :user => @one)
Title.create!(:title => '[one of Miriam\'s] The Easy Way To Self-Immolation', :user => @one)
Title.create!(:title => 'The Pacifist\'s Path To Passive-Aggressiveness', :user => @one)
Title.create!(:title => 'Lassie\'s Guide To Suicide Bombing', :user => @one)
Title.create!(:title => 'Genghis Khan The Genghis Khuddly: A Bold New Autobiography', :user => @one)
Title.create!(:title => 'Jesus Is To Stalin As Clark Kent Is To Superman: The Debate Rages On', :user => @one)
Title.create!(:title => 'Why Mexico Should Be Illegal', :user => @one)
Title.create!(:title => 'Babysitting With The Aryan Brotherhood', :user => @one)
Title.create!(:title => 'Debunking The Myth Of The Male Libido', :user => @one)
Title.create!(:title => 'Defeating Peak Oil: Drive Everywhere In Reverse, Enjoy Negative Fuel Consumption', :user => @one)
Title.create!(:title => 'Making Anthrax With Voltron', :user => @one)
Title.create!(:title => 'Methamphetamine: A Delightful Alternative To Breast Milk', :user => @one)
Title.create!(:title => 'Why Myrrh Was The Lousiest Of The Three Gifts', :user => @one)
Title.create!(:title => 'Asbestos: *Its* Side Of The Story', :user => @one)
Title.create!(:title => 'Dealing With Parking Tickets, And Other Deployments Of The 82nd Airborne', :user => @one)
Title.create!(:title => 'What The World Wars Taught Us About Dildos', :user => @one)
Title.create!(:title => 'Two Words: A Description Of The Book', :user => @one)
Title.create!(:title => 'Achieve More Meaningful Puppy-Raising With Anthrax', :user => @one)
Title.create!(:title => 'More Effective Global Conflict Resolution: Protoss Or Zerg?', :user => @two)
Title.create!(:title => 'Oh Go On, Just The Tip', :user => @two)
Title.create!(:title => 'Achieve More Spiritual Dating Through Rohypnol', :user => @two)
Title.create!(:title => 'Forced Mormon Conversion: A More Soothing Solution To The Arab/Israeli Conflict', :user => @two)
Title.create!(:title => '"Why Are You Doing This? Stop Stabbing Me", And Other Last Words I Have Enjoyed', :user => @two)
Title.create!(:title => 'Nations I have Sold My Children To', :user => @two)
Title.create!(:title => 'A Great Moral And Spiritual Leader: An Autobiography Of Hugh Hefner', :user => @two)
Title.create!(:title => 'Our Tapeworms, Ourselves', :user => @two)
Title.create!(:title => 'More Meaningful Post-Natal Surgery With Bandsaws', :user => @two)
Title.create!(:title => 'Ant-burning, And Other Uses For The Disabled Kid\'s Glasses: Let\'s Face It, They\'re Wasted On Him Anyway', :user => @two)
Title.create!(:title => 'Do-It-Yourself Wisdom Teeth Removal', :user => @two)
Title.create!(:title => 'Children I Have Given Candy To', :user => @two)
Title.create!(:title => 'Assault Rifles For The Under-Fives', :user => @two)
Title.create!(:title => '101 Ways To Cook Hello Kitty', :user => @two)
Title.create!(:title => 'Silence Is Golden, Duct Tape Is Silver', :user => @two)
Title.create!(:title => 'Ebola Popsicles, And Other Things To Sell Local Schoolkids', :user => @two)
Title.create!(:title => 'The Idiot\'s Guide To Buying Children Online', :user => @two)
Title.create!(:title => 'Syphilis And Other Thrifty Gifts For The Holidays', :user => @two)
Title.create!(:title => 'Home Butchery: How To Butcher An Ewok', :user => @two)
Title.create!(:title => 'Death Comes Quickly For Care Bears', :user => @two)
Title.create!(:title => 'Why The Trendiest Birthing Pools Use Tabasco Sauce', :user => @two)
Title.create!(:title => 'Superglue: The Personal Lubricant All The Cool Kids Use', :user => @two)
Title.create!(:title => 'Why Domestic Cats Make Superb Reactive Armour', :user => @two)
Title.create!(:title => 'Why Jesus Is The Antichrist', :user => @two)
Title.create!(:title => 'How Mother Teresa\'s Vibrators Power The Earth\'s Rotation', :user => @two)
Title.create!(:title => 'Don\'t Let The Bedbugs Steal Our Jobs', :user => @two)
Title.create!(:title => 'How Tactical Bacon Bested The SS', :user => @two)
Title.create!(:title => 'Plasma Burns: Nature\'s Learning Curve', :user => @two)
Title.create!(:title => 'Never Have Brazilian Waxes Again: How To Superglue Razorblades To A Condom', :user => @two)
Title.create!(:title => '34 Places It\'s Legal To Marry A Cat', :user => @two)
Title.create!(:title => 'Tampons Of Our Forefathers', :user => @two)
Title.create!(:title => 'Why Your Hair Wants You Dead', :user => @two)
Title.create!(:title => 'Jesus: The Ultimate Troll', :user => @two)
Title.create!(:title => 'Conquering Russia The Buddhist Way', :user => @two)
Title.create!(:title => 'Surviving The Rape Basement: My Life With Batman', :user => @two)
Title.create!(:title => 'Making The Perfect Christmas Dinner: Teaching Your Turkeys About Cannibalism', :user => @two)
Title.create!(:title => 'Why Warren Buffet Is Secretly Planning To Sellotape The Moon To The Sun', :user => @two)
Title.create!(:title => 'Tom Cruise: Mainstream Theologian', :user => @two)
Title.create!(:title => 'Martin Luther King: He Had A Homoerotic Dream', :user => @two)
@t1 = Title.create!(:title => 'The Story Of Adam, Eve, And Lindsay The Transsexual', :user => @two)
@t2 = Title.create!(:title => 'Eleven Different Colours, All Of Which Have Appeared On My Penis', :user => @two)
@t3 = Title.create!(:title => 'Romeo And Juliet: Re-enacting The Censored Gangbang Scene', :user => @two)
@t4 = Title.create!(:title => 'Achieve Transcendental Sexual Bliss With Velcro Condoms', :user => @two)
@t5 = Title.create!(:title => 'A Cure For Wedgies: Fact Or Fiction?', :user => @two)
@t6 = Title.create!(:title => 'Pirates: keeping parrots and the letter R in business', :user => @two)
@t7 = Title.create!(:title => '"What Are YOU Looking At?" A Passive-Aggressive Guide To Squinting [courtesy of Chris Addison]', :user => @two)
@t8 = Title.create!(:title => 'F Club Feven: A History Of Pop In The Tudor Era [courtesy of Chris Addison]', :user => @two)

20.times do
  @i1 = Illustration.create!(:illustration => File.open(File.join(Rails.root, '/public/images/0.jpg')), :user => @one)
  @i2 = Illustration.create!(:illustration => File.open(File.join(Rails.root, '/public/images/20090707034905142.jpg')), :user => @two)
  @i3 = Illustration.create!(:illustration => File.open(File.join(Rails.root, '/public/images/Bartrum1.jpg')), :user => @one)
  @i4 = Illustration.create!(:illustration => File.open(File.join(Rails.root, '/public/images/deavaandmitenthewave.png')), :user => @two)
  @i5 = Illustration.create!(:illustration => File.open(File.join(Rails.root, '/public/images/IMG_0375-726149.JPG')), :user => @one)
  @i6 = Illustration.create!(:illustration => File.open(File.join(Rails.root, '/public/images/Interlaken.jpg')), :user => @two)
  @i7 = Illustration.create!(:illustration => File.open(File.join(Rails.root, '/public/images/meadow.jpg')), :user => @one)
  @i8 = Illustration.create!(:illustration => File.open(File.join(Rails.root, '/public/images/the_iss.jpg')), :user => @two)
  
  Cover.create!(:title => @t1, :illustration => @i1)
  Cover.create!(:title => @t2, :illustration => @i2)
  Cover.create!(:title => @t3, :illustration => @i3)
  Cover.create!(:title => @t4, :illustration => @i4)
  Cover.create!(:title => @t5, :illustration => @i5)
  Cover.create!(:title => @t6, :illustration => @i6)
  Cover.create!(:title => @t7, :illustration => @i7)
  Cover.create!(:title => @t8, :illustration => @i8)
end
  

